name: macOS-local-clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{!contains(github.event.pull_request.title, 'skip-ci') && !contains(github.event.head_commit.message, 'skip-ci')}}
    strategy:
      matrix:
        build_type: [ Release ]
        os: [macos-latest]
        compiler:
          - cc: cc
            cxx: c++

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
      LLVM_VERSION: 17.0.2

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install llvm@17
      run: |
        brew install llvm@17
        echo $(brew --prefix llvm@17)/bin >> $GITHUB_PATH

    - name: Install cppsafe
      if: github.event_name == 'pull_request'
      run: brew install qqiangwu/tap/cppship

    - name: Format
      if: github.event_name == 'pull_request'
      run: |
        mergebase=$(git merge-base --fork-point origin/${{github.event.pull_request.base.ref}})
        cppship fmt -c ${mergebase}

    - name: Install conan
      run: pip3 install conan

    - name: Configure CMake
      run: |
        local_clang=$(brew --prefix llvm@17)
        echo "local clang: ${local_clang}"
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DLOCAL_CLANG=${local_clang} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Lint
      if: github.event_name == 'pull_request'
      run: |
        mergebase=$(git merge-base --fork-point origin/${{github.event.pull_request.base.ref}})
        clang-tidy --version
        cppship lint -c ${mergebase}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }} -j

    - name: Install
      if: github.event_name == 'pull_request'
      run: mv build/cppsafe $(brew --prefix llvm@17)/bin/

    - name: Test with RocksDB
      if: github.event_name == 'pull_request'
      run: |
        git clone https://github.com/qqiangwu/rocksdb-analysis.git
        cd rocksdb-analysis
        CC=$(brew --prefix llvm@17)/bin/clang CXX=$(brew --prefix llvm@17)/bin/clang++ cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_GFLAGS=OFF -DROCKSDB_BUILD_SHARED=OFF
        find . -name '*.cc' | sort | xargs -L 1 -I {} -P 3 -t bash -c "cppsafe -p build {} 2>&1" > me.log || true
        grep warning: me.log | sort | uniq -c | sort -k1n

    - uses: actions/upload-artifact@v4
      if: github.event_name == 'pull_request'
      with:
        name: rocksdb-result
        path: rocksdb-analysis/me.log

    - name: Check results
      if: github.event_name == 'pull_request'
      working-directory: rocksdb-analysis
      run: |
        [[ ! $(grep "Stack dump" me.log) ]] || (tail -n 100 me.log && false)