name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    if: ${{!contains(github.event.pull_request.title, 'skip-ci') && !contains(github.event.head_commit.message, 'skip-ci')}}
    strategy:
      matrix:
        build_type: [ Release ]
        os: [macos-12]
        compiler:
          - cc: cc
            cxx: c++

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
    - uses: actions/checkout@v3

    - name: Cache Conan2
      id: cache-conan2
      uses: actions/cache@v3
      with:
        path: ~/.cppsafe
        key: ${{ runner.os }}-${{ runner.arch }}-cppsafe-conan

    - name: Generate Prime Numbers
      if: steps.cache-conan2.outputs.cache-hit != 'true'
      run: cp -r lib ~/.cppsafe

    - name: Use Prime Numbers
      run: ls -l ~/.cppsafe
